### ISSUE TITLE
"App Not installed"

### ISSUE THREAD

**Issue by talhaidris7** [elastos/Elastos.App.Wallet.Android#102]
Getting an "App not installed" issue when trying to install APK
Devices: Samsung Galaxy Note 8 and Note 9 
Android Version: 8.1

**Comment by Arfanmi** [comment]
Uninstall Trinity DApp and then try again, that worked for me

**Comment by JeanMaritain** [comment]
Please install latest edition (https://github.com/elastos/Elastos.App.Wallet.Android/releases/download/v0.1.3/elawallet_a2586b6829_v0.1.3_MainNet.apk).
remember to backup your wallet data before your reinstallation.
