### ISSUE TITLE
wallet-dev branch:[Android钱包][钱包管理]钱包管理页面更改支付钱包图标缺失

### ISSUE THREAD

**Issue by TinaLingZhang** [elastos/Elastos.App.Wallet.Android#129]
节点环境：regtest
终端环境：iPhone 7 + 版本号 0.1.3 + spvsdk v0.2.1-194-ge0187d5(commit 92979b96-dirty_RegTest)

步骤：
1、已创建钱包终端启动钱包APP，自动跳转至首页
2、依次点击“设置-钱包管理”，查看更改支付密码菜单图标未正确显示
![20190225- -](https://user-images.githubusercontent.com/46308501/53341042-70d45100-3945-11e9-83ec-7f4a2f44600f.png)

实际结果：钱包管理页面更改支付钱包图标缺失
预期结果：正常显示资源图片

**Comment by songjiazhun** [comment]
#129 已修复 @TinaLingZhang

**Comment by TinaLingZhang** [comment]
测试通过
