### ISSUE TITLE
wallet-dev branch:[Android钱包][我要投票]选举管理页面执行注销操作，一直处于Loading状态，未生成注销交易

### ISSUE THREAD

**Issue by TinaLingZhang** [elastos/Elastos.App.Wallet.Android#130]
节点环境：regtest
终端环境：小米Max + 版本号 0.1.3 + spvsdk v0.2.1-194-ge0187d5(commit 92979b96-dirty_RegTest)

步骤：
1、已创建钱包终端启动钱包APP，自动跳转至首页
2、切换至某已参与候选钱包
3、依次点击“设置-我要投票-选举管理“，进入选举管理界面
4、点击【注销】按钮，查看一直处于Loading状态，未生成注销交易
[20190227-注销producer持续Loading状态.txt](https://github.com/elastos/Elastos.App.Wallet.Android/files/2908756/20190227-.producer.Loading.txt)

实际结果：选举管理页面执行注销操作，一直处于Loading状态，未生成注销交易
预期结果：注销参选成功，生成注销交易，返回质押金

**Comment by songjiazhun** [comment]
#130 已修复 @TinaLingZhang

**Comment by TinaLingZhang** [comment]
测试通过
